class Parque {
    -Nombre: String
    -Ubicacion: String
    -Superficie: Double
}

class Guardaparque {
    -Nombre: String
    -Antiguedad: Integer
    -Especialidad: String
}

class Atraccion {
    -Nombre: String
    -Tipo: String
    -Precio: Double
}

' Relaciones
Parque "1" -- "*" Atraccion : Tiene
Parque "1" -- "*" Guardaparque : Emplea
Guardaparque "1" -- "*" Atraccion : Vigila
